### ISSUE TITLE
hover broken for newly loaded dom elements

### ISSUE THREAD

**Issue by jessehart** [keithclark/selectivizr#16]
in ie7 (could be ie6+ie8 as well) selectivizr seems to break the hover states for ajax loaded dom elements

jquery 1.6.1, selectivizr 1.0.3b (and lower)

**Comment by keithclark** [comment]
Do you have an online example I can look at?

**Comment by jessehart** [comment]
conflict with something else, not sure yet

**Comment by keithclark** [comment]
If you get to the bottom of it could you let me know what the problem was?

**Comment by skrivle** [comment]
This one is still an active issue. 

The problem occurs when new elements are added to the DOM after selectivizr has initialized. 

The script removes all the :hover rules from the css file and replaces them with a class like .hover or something. Then Selectivizr binds an event handler that toggles this class on and off to all of the elements that match the given selector. The problem is that for all elements generated by javascript there isn't such an event handler available and thus the .hover class will not be toggled on and off. As a result no hover effect will be shown. 

A solution could be making use of event delegation although I'm not sure what that would mean performance wise ...

**Comment by johndugan** [comment]
I am experiencing the same issue with Selectivizr and the :hover event. Any update on this? Currently running version 1.0.3b.

**Comment by aokros** [comment]
This issue is still present. Do you need some help in resolving? We are trying to use selectivizr in an SPA that runs on Angular.js, but this defect makes it impossible...
