### ISSUE TITLE
nth-child() works for IE7, 9, and 10, but not 8

### ISSUE THREAD

**Issue by corysimmons** [keithclark/selectivizr#45]
Anyone else have this problem?

**Comment by hartwm** [comment]
yep... any help? 
tried compatibility tags, older jquery versions, dtd, nothing seems to work

**Comment by dottodot** [comment]
I just can't nth-child to work

Using this

.row .col:nth-child(4n+1)

only the first child is selected

**Comment by joshbtn** [comment]
Seeing the same thing in IE10 when in IE7 Browser/Document Mode w/ jQuery 1.8.2.

It's adding the class to the first child, 5th, 9th ... 

_Update_
I found this, but i'm still seeing the same issue. This fixed a few other problems however.
https://github.com/keithclark/JQuery-Extended-Selectors

_Update_
Turns out jQuery doesn't handle :nth-child(4n+1) In the way i was expecting.

**Comment by chrispropane** [comment]
+1

**Comment by noname01** [comment]
same problem
